#!/bin/bash
#Purpose = Backup of Important Data
#Version 1.1
#START

TIME=`date +%b-%d-%y` # This Command will add date in Backup File Name.
FILENAME=backup-$TIME.tar.gz # Here i define Backup file name format.

SRCDIR1=public_html/xxx1 # Source Directory 1.
SRCDIR2=public_html/xxx2 # Source Directory 2.
SRCDIR3=/home/xxxx/public_html/xx3 # Source Directory 3.

DESDIR=public_html/xxx # Destination of backup file.

tar -cpzf $DESDIR/$FILENAME $SRCDIR1 $SRCDIR2 $SRCDIR3

#END
